version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: social-network
      POSTGRES_USER: bojana
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: